import type { Analyst, AssignmentRecord, AuthenticatedUser } from '../models/types';

export const supervisorUser: AuthenticatedUser = {
  id: '1',
  displayName: 'S. Grant',
  role: 'supervisor',
  canManageAssignments: true,
  canViewSensitiveData: true,
};

export const readOnlySupervisorUser: AuthenticatedUser = {
  ...supervisorUser,
  id: '2',
  canManageAssignments: false,
};

export const analystReidUser: AuthenticatedUser = {
  id: '3',
  displayName: 'A. Reid',
  role: 'analyst',
  canManageAssignments: false,
  canViewSensitiveData: false,
};

export const analystCampbellUser: AuthenticatedUser = {
  id: '4',
  displayName: 'B. Campbell',
  role: 'analyst',
  canManageAssignments: false,
  canViewSensitiveData: false,
};

export const analystsFixture: Analyst[] = [
  {
    id: '3',
    displayName: 'A. Reid',
    department: 'Food Chemistry',
    activeStatus: 'Active',
    workload: { total: 2, inProgress: 1, overdue: 0, completed: 1 },
  },
  {
    id: '4',
    displayName: 'B. Campbell',
    department: 'Toxicology',
    activeStatus: 'Active',
    workload: { total: 1, inProgress: 1, overdue: 1, completed: 0 },
  },
  {
    id: '7',
    displayName: 'C. Morris',
    department: 'Microbiology',
    activeStatus: 'Inactive',
    workload: { total: 0, inProgress: 0, overdue: 0, completed: 0 },
  },
];

export function buildAssignmentRecordsFixture(): AssignmentRecord[] {
  return [
    {
      assignment: {
        id: 'assignment-1',
        sampleId: 'sample-1',
        testId: 'test-1',
        analystId: '3',
        assignedBy: '1',
        assignedByName: 'S. Grant',
        assignedDateTime: '2026-08-20T10:00:00Z',
        status: 'In Progress',
        dueDateTime: '2026-08-25T00:00:00Z',
        priority: 'Routine',
        overdue: false,
        reassignmentReason: null,
      },
      sample: {
        id: 'sample-1',
        accessionNumber: 'FOOD-001',
        sampleName: 'Milk Sample',
        sampleType: 'Food (Milk)',
        location: 'Kingston',
        receivedDateTime: '2026-08-18T09:00:00Z',
        status: 'Registered',
      },
      test: {
        id: 'test-1',
        sampleId: 'sample-1',
        testName: 'Fat Content',
        testReference: null,
        dueDateTime: '2026-08-25T00:00:00Z',
        status: 'In Progress',
        priority: 'Routine',
        assignedAnalystId: '3',
        assignedBy: '1',
        assignedDateTime: '2026-08-20T10:00:00Z',
        completedDateTime: null,
        workItemUrl: '/samples/assignment/12',
      },
      analyst: analystsFixture[0],
      history: [
        {
          id: 'history-1',
          action: 'Assigned',
          details: 'Assigned to A. Reid.',
          performedBy: '1',
          performedDateTime: '2026-08-20T10:00:00Z',
        },
      ],
    },
    {
      assignment: {
        id: 'assignment-2',
        sampleId: 'sample-2',
        testId: 'test-2',
        analystId: '4',
        assignedBy: '1',
        assignedByName: 'S. Grant',
        assignedDateTime: '2026-08-19T08:15:00Z',
        status: 'Completed',
        dueDateTime: '2026-08-21T00:00:00Z',
        priority: 'STAT',
        overdue: false,
        reassignmentReason: null,
      },
      sample: {
        id: 'sample-2',
        accessionNumber: 'TOX-014',
        sampleName: 'Blood Sample',
        sampleType: 'Clinical',
        location: 'Montego Bay',
        receivedDateTime: '2026-08-17T09:00:00Z',
        status: 'Registered',
      },
      test: {
        id: 'test-2',
        sampleId: 'sample-2',
        testName: 'Blood Alcohol',
        testReference: 'FAP-001',
        dueDateTime: '2026-08-21T00:00:00Z',
        status: 'Completed',
        priority: 'STAT',
        assignedAnalystId: '4',
        assignedBy: '1',
        assignedDateTime: '2026-08-19T08:15:00Z',
        completedDateTime: '2026-08-20T15:00:00Z',
        workItemUrl: '/samples/assignment/13',
      },
      analyst: analystsFixture[1],
      history: [
        {
          id: 'history-2',
          action: 'Completed',
          details: 'Results finalized.',
          performedBy: '4',
          performedDateTime: '2026-08-20T15:00:00Z',
        },
      ],
    },
    {
      assignment: {
        id: 'assignment-3',
        sampleId: 'sample-3',
        testId: 'test-3',
        analystId: null,
        assignedBy: null,
        assignedByName: null,
        assignedDateTime: null,
        status: 'Assigned',
        dueDateTime: null,
        priority: 'Urgent',
        overdue: false,
        reassignmentReason: null,
      },
      sample: {
        id: 'sample-3',
        accessionNumber: 'MICRO-009',
        sampleName: 'Water Sample',
        sampleType: 'Environmental',
        location: 'Spanish Town',
        receivedDateTime: null,
        status: 'Registered',
      },
      test: {
        id: 'test-3',
        sampleId: 'sample-3',
        testName: 'Microbial Count',
        testReference: null,
        dueDateTime: null,
        status: 'Assigned',
        priority: 'Urgent',
        assignedAnalystId: null,
        assignedBy: null,
        assignedDateTime: null,
        completedDateTime: null,
        workItemUrl: '/samples/assignment/14',
      },
      analyst: null,
      history: [],
    },
    {
      assignment: {
        id: 'assignment-4',
        sampleId: 'sample-4',
        testId: 'test-4',
        analystId: '4',
        assignedBy: '1',
        assignedByName: 'S. Grant',
        assignedDateTime: '2026-08-18T09:00:00Z',
        status: 'Rejected',
        dueDateTime: '2026-08-20T00:00:00Z',
        priority: 'Routine',
        overdue: true,
        reassignmentReason: 'Returned by reviewer',
      },
      sample: {
        id: 'sample-4',
        accessionNumber: 'CHEM-110',
        sampleName: 'Tablet Sample',
        sampleType: 'Pharmaceutical',
        location: 'Kingston',
        receivedDateTime: '2026-08-15T09:00:00Z',
        status: 'Registered',
      },
      test: {
        id: 'test-4',
        sampleId: 'sample-4',
        testName: 'Dissolution',
        testReference: 'USP 711',
        dueDateTime: '2026-08-20T00:00:00Z',
        status: 'Rejected',
        priority: 'Routine',
        assignedAnalystId: '4',
        assignedBy: '1',
        assignedDateTime: '2026-08-18T09:00:00Z',
        completedDateTime: null,
        workItemUrl: '/samples/assignment/15',
      },
      analyst: analystsFixture[1],
      history: [
        {
          id: 'history-4',
          action: 'Rejected',
          details: 'Reviewer requested correction.',
          performedBy: '1',
          performedDateTime: '2026-08-20T11:30:00Z',
        },
      ],
    },
  ];
}
